### ISSUE TITLE
Error creating users

### ISSUE THREAD

**Issue by jchiavaro** [ArgenissSoftware/jared-frontend#54]
After sending the data for creating a new user, I get the following error:
![screen shot 2018-07-16 at 10 29 34](https://user-images.githubusercontent.com/1855375/42761579-4f998d0a-88e4-11e8-8787-7df90901fc70.png)

**Comment by AHerbel** [comment]
Como dijo @lrabuffetti hay un error en la respuesta del servicio de Login. Esta devolviendo un objeto como este: { message: "Login correct!" } en el objeto "data" de la respuesta, cuando se espera un objeto Usuario como respuesta (no pongo la estructura del objeto Usuario porque no conozco exactamente cual es). No creo un branch para resolver este issue porque creo que la solución al problema esta en el backend, no en el front. De todas formas adjunto fotos del track que hice para concluir esto:

AuthStore.js
![login-error-jarederp](https://user-images.githubusercontent.com/22715296/43108083-6baa363e-8eb6-11e8-9d43-c7da18c6e88d.PNG)

login-top-nav-bar.js
![login-top-navbar](https://user-images.githubusercontent.com/22715296/43108124-a682c974-8eb6-11e8-8c35-d87b497aa0a9.PNG)

AuthStore.js
![authstore](https://user-images.githubusercontent.com/22715296/43108131-acd25aa6-8eb6-11e8-8ae6-fb21cda3c124.PNG)
